### ISSUE TITLE
Explain what the project does

### ISSUE THREAD

**Issue by stimms** [aspnet/UserSecrets#13]
The readme should contain some hints as to what this project does. I've read the source and other than encrypting secrets I have no idea of its purpose. Are these connection strings that are encrypted? Passwords? The membership lists for the illuminati?

**Comment by BrennanConroy** [comment]
Read this for now: https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration

**Comment by ericis** [comment]
Found this useful... so +1 until closed :D

**Comment by Eilon** [comment]
Is there any more to say here? The readme now links to some docs that describe the feature. Please reopen if you feel there's something important missing. Thanks!
