### ISSUE TITLE
Keys-Only Export and Import

### ISSUE THREAD

**Issue by MisterJames** [aspnet/UserSecrets#14]
Not sure if this is in the cards, but a thought that came to mind would be to have an artifact generated on build that shipped when publishing a project.

I'm thinking of the situation where you have a number of variables defined and stored in secrets, these may not be evident/exposed without some digging into code.

So back to the idea: use an overload of the list command (or an export command?) as part of build to dump a JSON file to the output directory. If Kudu then picked up that artifact on deployment, it could then create placeholder values in the web app. Of course, if stored as JSON, any deployment script could read it and configure the hosting environment.

Maybe this isn't the right project for this, but it should be the right set of eyeballs. :)

**Comment by MisterJames** [comment]
So, I'm looking at this again as I've been thinking about the flow of a project. I'm thinking there is going to be value in doing two things:

  1. Exporting via a `keys` command, which would export the list of keys as JSON sans values
  2. Adding keys through an `import` command, which would take a JSON list of keys and add them to the secrets.

There would be additional value in prompting on import for any blank values (though, not requiring values explicitly), but that could come later.

Of the two listed above, I've started the `keys` command, which is following the same pattern as the `list` command.  This is a minimal start to this concept, and would easily allow a developer to share her secret keys (without values) with an onboarding team member.

I figured I'd see if there was support for this before I tossed up a PR.  

Thoughts?

**Comment by muratg** [comment]
@MisterJames If you're still up for a PR, we'll have a look.  Otherwise this won't make it in V1.

**Comment by natemcmaster** [comment]
This repository is now deprecated. I'm closing this issue as we don't intend to take further action to address this issue. If you feel this issue should still be addressed, issues for UserSecrets can be opened on its new home at https://github.com/aspnet/DotNetTools.

cref https://github.com/aspnet/Announcements/issues/206.
