### ISSUE TITLE
Install failure - error in project.json

### ISSUE THREAD

**Issue by mattdwen** [aspnet/UserSecrets#15]
I'm attempting to install SecretManager via the following command line with dnu` v1.0.0-beta5-11566:

`dnu commands install SecretManager`

However the install fails, referencing an error in the SecretManager project.json:

```
PS C:\Projects\diva-focus> dnu commands uninstall SecretManager
SecretManager command is not installed.
PS C:\Projects\diva-focus> dnu commands install SecretManager
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='SecretManager'
Restoring packages for C:\Users\Matt Dwen\.dnx\bin\packages\7aa68819f2a0433d874c2922bdccf39b\project.json
Writing lock file C:\Users\Matt Dwen\.dnx\bin\packages\7aa68819f2a0433d874c2922bdccf39b\project.lock.json
Restore complete, 238ms elapsed
Restoring packages for C:\Users\Matt Dwen\.dnx\bin\packages\SecretManager\1.0.0-beta4\app\project.json
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='SecretManager'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Console'
Unable to locate SecretManager >= 1.0.0-beta4-10173
Writing lock file C:\Users\Matt Dwen\.dnx\bin\packages\SecretManager\1.0.0-beta4\app\project.lock.json
Restore complete, 149ms elapsed
Errors in C:\Users\Matt Dwen\.dnx\bin\packages\SecretManager\1.0.0-beta4\app\project.json
    Unable to locate SecretManager >= 1.0.0-beta4-10173
```

The package ends up inside `C:\Users\Matt Dwen\.dnx\bin\packages\SecretManager\1.0.0-beta4` but attempting to execute `user-secret` results in a PowerShell `ObjectNotFound` dump.

**Comment by bmancini55** [comment]
I'm seeing the same.  Did you find a resolution?

**Comment by davidfowl** [comment]
There are some regressions with beta5

**Comment by BrennanConroy** [comment]
Did you install SecretManager before? Cause your uninstall is wrong, you need to do uninstall user-secret

**Comment by mattdwen** [comment]
I have not installed SecretManager before.
Have also attempted on a clean Win10 VM.

**Comment by BrennanConroy** [comment]
Like David said, there is a regression, but it doesn't apply to your version of dnx probably. Also, are your nuget feeds pointing to nuget.org? Because you are getting beta4 versions. Don't cross the streams!

**Comment by rajeshchawla** [comment]
Understand it's a regression, any thoughts for a workaround?

**Comment by BrennanConroy** [comment]
Use beta4 or beta5 less than version ~11582

**Comment by rajeshchawla** [comment]
Not quite sure how to do that.

I'm missing how to specify the version on the dnu command install and the command Install-Package SecretManager -Pre in the powershell console doesn't seem to get the right version. 

Any hints?

**Comment by markrendle** [comment]
I'm using beta4 (dnx-mono) on Ubuntu and getting the same error.

**Comment by sksbrg** [comment]
Hi, I experienced the same issue. Solved it locally but adjusting version number in `project.json` locally; see linked issue (https://github.com/aspnet/Home/issues/601#issuecomment-102780011).

With kind regards,
Stefan

**Comment by freecellwiz** [comment]
I followed Stefan's suggestion above and this resolved the problem for me.

**Comment by mattdwen** [comment]
Yup, Stefan's fix worked for me as well.
