### ISSUE TITLE
SecretManager should display its own version information

### ISSUE THREAD

**Issue by Tratcher** [aspnet/UserSecrets#23]
When using secret manager it's not clear what version you are using. The only way to find out at the moment is to edit `c:\users\%userprofile%\.dnx\bin\user-secret.cmd`.

Recommendation: `user-secret -h` should display the version of the utility.

**Comment by MisterJames** [comment]
I can implement this one, should I start a PR?

**Comment by Tratcher** [comment]
Go for it.

**Comment by MisterJames** [comment]
@Tratcher Just had to set a couple of props on the `CommandLineApplication`. Please let me know if you have any feedback, should be complete with PR#32.
