### ISSUE TITLE
Clearing a corrupted secrets.json file

### ISSUE THREAD

**Issue by Tratcher** [aspnet/UserSecrets#24]
The secrets.json file can be directly edited by the user, and as such is subject to typos and other corruption. Once corrupted all operations fail with json parsing errors and the file cannot be fixed/cleared/deleted by user-secret. Instead you have to go find the file and correct it by hand.

Recommendation: `user-secret clear` should overwrite the file without attempting to parse it. This will allow you to easily recover from corrupted files.

**Comment by MisterJames** [comment]
I'll pick this one up. Creating a branch/PR for it to get it started.

**Comment by MisterJames** [comment]
@Tratcher I think I got this wrapped...but I'm getting a merge conflict message on GitHub that I don't see on my side. I'll see what I can figure out, but if you see something, please let me know. I haven't seen this state before. :/

**Comment by BrennanConroy** [comment]
Pull the latest dev rebase your PR on it.

**Comment by MisterJames** [comment]
Thanks @BrennanConroy Seems it didn't clear it. Sorry if I'm dense.  I did a:

    git fetch aspnet
    git rebase aspnet/dev

That seems to have added your last merge, but has not cleared the conflict here on GH.

I did this also on #32 / #23. Did I do something wrong?

**Comment by MisterJames** [comment]
@BrennanConroy After the interactive rebase to squash, I had to also do a `push -f`. 

Everything is in a single commit now on both PRs, hopefully they merge cleanly. 

Cheers.

**Comment by BrennanConroy** [comment]
527119a2178860ca1c0a3d70587ea4e023473f2d
