### ISSUE TITLE
Remove CommandOutputLogger, and use ConsoleLogger instead

### ISSUE THREAD

**Issue by kichalla** [aspnet/UserSecrets#27]
I would like to use the [CommandOutputLogger](https://github.com/aspnet/UserSecrets/blob/dev/src/SecretManager/CommandOutputLogger.cs#L13) for the global command that I have in SqlServer distributed cache package.

Should we move this logger out to some common location so that other packages can use it?
/cc: @Eilon @davidfowl

**Comment by Eilon** [comment]
Instead of being shared source, should we just make it be a proper public implemented of `ILogger`? I'm also wondering why this is different from the current Console Logger.

**Comment by kichalla** [comment]
> I'm also wondering why this is different from the current Console Logger.

Looks like it was meant to avoid seeing the prefix text like `error: [Microsoft.Framework.Caching.SqlServerCache]` when showing any information related to the command on the console. Line below:
https://github.com/aspnet/UserSecrets/blob/dev/src/SecretManager/CommandOutputLogger.cs#L43

**Comment by Eilon** [comment]
Hmm, but that's the weird thing - it *does* show error/critical/etc. as a prefix...

**Comment by kichalla** [comment]
@Eilon : yeah, you are right...I think its ok to show the logger name...probably we should remove this logger entirely and just use ConsoleLogger?

/cc: @BrennanConroy

**Comment by BrennanConroy** [comment]
I think that would be fine.

**Comment by natemcmaster** [comment]
This repository is now deprecated. We can address improvements like this on the new shared tools repo.

https://github.com/aspnet/Announcements/issues/206.
