### ISSUE TITLE
The name 'AddUserSecrets' does not exist in the current context

### ISSUE THREAD

**Issue by back5576** [aspnet/UserSecrets#29]
Have this

```c#
            var builder = new ConfigurationBuilder(appEnv.ApplicationBasePath)
                .AddJsonFile("config.json")
                .AddJsonFile($"config.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
                .AddUserSecrets();
            Configuration = builder.Build();
```

And get error

The name 'AddUserSecrets' does not exist in the current context

**Comment by BrennanConroy** [comment]
Does your project.json include the Microsoft.Framework.Configuration.UserSecrets package?

**Comment by back5576** [comment]
I did, but I had first had
Microsoft.Framework.ConfigurationModel.UserSecrets
and then changed to
Microsoft.Framework.Configuration.UserSecrets

startup.cs has

using Microsoft.Framework.Configuration.UserSecrets;

**Comment by BrennanConroy** [comment]
You realize you have a semi-colon after AddEnvironmentVariables()...

**Comment by back5576** [comment]
Good eye! That was indeed the issue.
