### ISSUE TITLE
SecretManager package name and namespaces seem to be wrong

### ISSUE THREAD

**Issue by Praburaj** [aspnet/UserSecrets#3]
Moved from https://github.com/aspnet/Configuration/issues/163

**Comment by Praburaj** [comment]
@davidfowl do you have any concerns on this change? The command name should still remain the same. Only the package is to be renamed.

**Comment by Praburaj** [comment]
@Eilon @muratg @glennc

**Comment by muratg** [comment]
This seems fine to me, unless we decide not to use namespaces for tools (which might be convenient.)  Would like to hear other folks' thoughts as well.

Not needed for Beta4 though.

**Comment by Eilon** [comment]
This is the same model as Kestrel. Kestrel itself (the tool) is just Kestrel.

**Comment by Praburaj** [comment]
@divega

**Comment by divega** [comment]
I am fine wit this. When I filed the original bug in Configuration we had just hit the package by accident while trying to do the branching and it seemed very weird to me, but at the time I didn't know it was actually a tool :smile:

**Comment by muratg** [comment]
Related: https://github.com/aspnet/UserSecrets/issues/6

**Comment by Praburaj** [comment]
We have an ongoing discussion in #6. So closing this one.
