### ISSUE TITLE
A question of usage style

### ISSUE THREAD

**Issue by back5576** [aspnet/UserSecrets#31]
I have in my test project

        public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
        {
            var builder = new ConfigurationBuilder(appEnv.ApplicationBasePath)
                .AddJsonFile("config.json")
                .AddJsonFile($"config.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables()
                .AddUserSecrets();
            Configuration = builder.Build();
        }

but I see others use:

        public Startup(IHostingEnvironment env, IApplicationEnvironment appEnv)
        {
            var builder = new ConfigurationBuilder(appEnv.ApplicationBasePath)
                .AddJsonFile("config.json")
                .AddJsonFile($"config.{env.EnvironmentName}.json", optional: true)
                .AddEnvironmentVariables();
            if (env.EnvironmentName =="Development" )
            {
                builder.AddUserSecrets();
            }
            Configuration = builder.Build();
        }

So I'm curious if there is a good rationale for doing the later with the conditional.

**Comment by Eilon** [comment]
I wouldn't say there's anything fundamentally wrong with always calling it. But in non-development scenarios there are unlikely to be any per-user secrets available, so it's unlikely to be useful.

**Comment by muratg** [comment]
User secrets are mainly used in development time.  In Azure App Services for example, you'll likely manage your secrets through Azure Portal, and will be able to access them from environment variables.
