### ISSUE TITLE
NullReferenceException with user-secret for any command

### ISSUE THREAD

**Issue by ricklove** [aspnet/UserSecrets#34]
I am following the instructions here:
http://docs.asp.net/en/latest/security/sociallogins.html

- I start the VS 2015 Developer Command Prompt in Administrator Mode:

- Open a Command Prompt and navigate to the folder of project.json for your project.
- Use DNVM (.NET Version Manager) to set a runtime version by running:
    - dnvm use 1.0.0-beta4
- Install the SecretManager tool using DNU (Microsoft .NET Development Utility) by running:
    - dnu commands install SecretManager
- Set the Facebook AppId by running:
    - user-secret set Authentication:Facebook:AppId 862373430475128

At this point I get an exception: NullReferenceException

C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp>user-secret help
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at SecretManager.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
   at SecretManager.Program..ctor(IRuntimeEnvironment runtimeEnv)

Console log below:
----

	C:\Windows\system32>cd C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp

	C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp>dnvm use 1.0.0-beta4
	Adding C:\Users\...\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta4\bin to pr
	ocess PATH

	C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp>dnvm list

	Active Version     Runtime Architecture Location                            Ali
																				as
	------ -------     ------- ------------ --------                            ---
		   1.0.0-beta4 clr     x64          C:\Users\...\.dnx\runtimes
	  *    1.0.0-beta4 clr     x86          C:\Users\...\.dnx\runtimes def
		   1.0.0-beta4 coreclr x64          C:\Users\...\.dnx\runtimes
		   1.0.0-beta4 coreclr x86          C:\Users\...\.dnx\runtimes

	C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp>dnu commands install SecretMa
	nager
	  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='SecretManager'
	Restoring packages for C:\Users\...\.dnx\bin\packages\b35711727c404fd08
	07f649dd45c8975\project.json
	Writing lock file C:\Users\...\.dnx\bin\packages\b35711727c404fd0807f64
	9dd45c8975\project.lock.json
	Restore complete, 325ms elapsed
	Restoring packages for C:\Users\...\.dnx\bin\packages\SecretManager\1.0
	.0-beta5\app\project.json
	  CACHE https://www.nuget.org/api/v2/FindPackagesById()?Id='System.Console'
	Writing lock file C:\Users\...\.dnx\bin\packages\SecretManager\1.0.0-be
	ta5\app\project.lock.json
	Restore complete, 484ms elapsed
	The following commands were installed: user-secret

	C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp>user-secret help
	System.NullReferenceException: Object reference not set to an instance of an obj
	ect.
	   at SecretManager.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
	   at SecretManager.Program..ctor(IRuntimeEnvironment runtimeEnv)

	C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp>user-secret ?
	System.NullReferenceException: Object reference not set to an instance of an obj
	ect.
	   at SecretManager.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
	   at SecretManager.Program..ctor(IRuntimeEnvironment runtimeEnv)

	C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp>user-secret
	System.NullReferenceException: Object reference not set to an instance of an obj
	ect.
	   at SecretManager.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
	   at SecretManager.Program..ctor(IRuntimeEnvironment runtimeEnv)

	C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp>user-secret set
	System.NullReferenceException: Object reference not set to an instance of an obj
	ect.
	   at SecretManager.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
	   at SecretManager.Program..ctor(IRuntimeEnvironment runtimeEnv)

	C:\Projects\Test\AspNet5\TestWepApp\src\TestWepApp>

**Comment by muratg** [comment]
@ricklove Does this still repro for you with the newer betas of DNX and user-secret commands? I couldn't repro this with beta7/beta8 so closing for now. If you still have issues, please reactivate.

**Comment by adrianhara** [comment]
I still get this with 1.0.0-rc1-final

**Comment by BrennanConroy** [comment]
You need to update the version of secret manager you have

**Comment by adrianhara** [comment]
You're right. I had run install before, but I think it used the existing version (beta8). I needed to run install with "--overwrite" to get the latest version and now it works fine. Thanks!

**Comment by gdillen** [comment]
I have also problems with 1.0.0.-rc1-final:

I installed "SecretManager" by running (in command prompt):

dnvm use 1.0.0-rc1-final
dnu commands install Microsoft.Framework.SecretManager --overwrite

After installing when running user-secret -h I get the following errors:

System.NullReferenceException: Object reference not set to an instance of an obj
 ect.
 at Microsoft.Framework.SecretManager.CommandOutputProvider..ctor(IRuntimeEnvironment runtimeEnv)
 at Microsoft.Framework.SecretManager.Program..ctor(IRuntimeEnvironment runtimeEnv)

Thanks.
 Guy

**Comment by gdillen** [comment]
Problem solved:
 "dnu commands install Microsoft.Extensions.SecretManager --overwrite" does the thing

**Comment by muratg** [comment]
@gdillen Yeah, the package for the command was renamed.

**Comment by markau** [comment]
I encountered this issue and the problem was that the `user-secret.cmd` was never added to my path. I need to `cd` to that directory in order to run the command.
