### ISSUE TITLE
Add cool ASCII art as part of help banner

### ISSUE THREAD

**Issue by MisterJames** [aspnet/UserSecrets#35]
DNX/EF/DNVM all have much cooler banners. I feel like UserSecrets needs some love, too.

**Comment by natemcmaster** [comment]
This repository is now deprecated. I'm closing this issue as we don't intend to take further action to address this issue. If you feel this issue should still be addressed, issues for UserSecrets can be opened on its new home at https://github.com/aspnet/DotNetTools.

cref https://github.com/aspnet/Announcements/issues/206.
