### ISSUE TITLE
critical: Command failed : Missing 'userSecretsId'

### ISSUE THREAD

**Issue by LeoNatanian** [aspnet/UserSecrets#36]
I stumbled upon the answer to the first of a series of problems I've been encountered when following the http://docs.asp.net/en/latest/security/sociallogins.html tutorial.  

After using the information I found here: https://github.com/aspnet/UserSecrets/issues/15 to solve the first problem, I'm now encountered a second problem where I get a critical error message reading Command failed : Missing 'userSecretsId' (see image below) when I runt he command user-secret set Authentication:Facebook:AppId XXXXXX.

![image](https://cloud.githubusercontent.com/assets/5349254/9323678/f4abb8ca-4537-11e5-9a78-9f00143941d5.png)

Is this an issue that is related to UserSecrets?

**Comment by BrennanConroy** [comment]
Add userSecretsId to your project.json

**Comment by LeoNatanian** [comment]
I went ahead and added userSecretsId to my project.json file.  I added two iterations of them:

1. "userSecretsId": ""
2. "userSecretsId": null

On both attempts, I got the following "critical: Command failed : Missing 'userSecretsId' in 'C:\Users\..."

This is the entire project.json file below

{
  "version": "1.0.0-*",
  "description": "ASP.NET 5 tool to manage user secrets.",
  "dependencies": { "SecretManager": "1.0.0-beta5" },
  "commands": { "user-secret": "SecretManager" },
  "frameworks": {
    "dnx451": { },
    "dnxcore50": { "dependencies": { "System.Console": "4.0.0-beta-*" } }
  },
  "entryPoint": "SecretManager",
  "loadable": false,
  "userSecretsId": ""
}

**Comment by BrennanConroy** [comment]
Why are you trying to add secrets to the global command?

This is for applications that you make.
You should never have to touch anything in the .dnx folder unless it is to manually delete folders.

**Comment by Eilon** [comment]
Set the `userSecretsId` to a non-empty value, such as a GUID or an application name.

**Comment by muratg** [comment]
@LeoNatanian The idea is to differentiate the user secrets of different applications that you might be working on your machine, so you give each app that uses this global command a different id by setting a value to `userSecretsId`.  After you do that, you should be able to add secrets. Closing this one, but if you continue to have problems, please leave a note and we can have a look.

**Comment by jhondev** [comment]
This could be help http://docs.asp.net/en/latest/security/app-secrets.html#security-app-secrets

**Comment by pauldotknopf** [comment]
I had this issue after migrating a project from RC1 to RC2. I was missing ```SetBasePath``` on my ```ConfigurationBuilder```.

```
var builder = new ConfigurationBuilder()
    .SetBasePath(env.ContentRootPath) // this line was missing
    .AddJsonFile("appsettings.json")
    .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true);
```
