### ISSUE TITLE
Rename Microsoft.Framework.* to Microsoft.Extensions.*

### ISSUE THREAD

**Issue by Eilon** [aspnet/UserSecrets#43]
Need to rename assemblies and namespaces from `Microsoft.Framework.*` to `Microsoft.Extensions.*`.

Once the change is committed, please post an issue in the https://github.com/aspnet/Announcements/issues/ repo that links back to this issue.

**Comment by pranavkm** [comment]
6a18bc754b5a2a89f8b094ac5ecbe883fea1a6e5
