### ISSUE TITLE
Generator extensibility - generating random crypto keys

### ISSUE THREAD

**Issue by ridercz** [aspnet/UserSecrets#44]
I'm missing a simple way to generate cryptographic keys (using CSPRNG, various lengths and encoding). I'm willing to write one, but I'm not sure where it belongs

The [wiki page](https://github.com/aspnet/Home/wiki/DNX-Secret-Configuration) asks for more generators:
> No other generators yet, but if you have one that works feel free to send a PR to add it to this list.
However, I am unable to find out how to write generators, where's the extensibility point. Can someone please point me somewhere?

Or, maybe the better idea is to generate the keys in the `user-secret` utility? Add new command with them?

**Comment by muratg** [comment]
@ridercz `user-secret` tool does not encrypt data, it's primary purpose is to keep secrets out of the project folder (such as a configuration file) so that they don't accidentally get checked in to a source tree, and it's purely a development time utility. 

So this kind of behavior (generating cryptographic keys) do not belong to this tool.  However, you can create another `global command` (see [this](http://docs.asp.net/en/latest/dnx/commands.html#global-commands) for more info) that you can release on NuGet, and use.

Does this help?

**Comment by ridercz** [comment]
@muratg: If `user-secret` is a development-time tool, where are we supposed to store secrets in production deployments?

As I understand it (and maybe I'm wrong, for the lack of conceptual documentation), at development time we can generally use default in-memory configuration with hardcoded values. It's in production, where we want to protect secrets most. And where we want to keep them out of configuration file, as protection against directory traversal bugs etc. 

So I see `user-secret` more as deployment-time tool (with potential for development-time use if putting development time secrets is not desirable). If I'm mistaken, what's the production deployment story like?

Also, if I create another global command, how I'm supposed to interact with the user secrets infrastructure? Writing directly to `secrets.json` the way `user-secret` utility does? Or call it somehow (can one global command call another?)

Or maybe there's some other "production secrets" infrastructure (to be) written? It would make sense for me to store the secrets in some more secure way than plain json file, maybe DPAPI on Windows and some equivalent on Linux...

**Comment by muratg** [comment]
@ridercz The tool is only for keeping development-time secrets out of source tree. Let's go through a scenario for the deployment:

- You create an web app that uses another service, and your secret is the API key for that service
- You have a test service that you use for development and an actual production service that you want to use in your app, so two separate keys
- You create a config name that you'll read the API key from, both in development and production
- You do `.AddUserSecrets` (only when Environment is Production) and `.AddEnvironmentVariables` on your `ConfigurationBuilder`
- You use user-secret to set the test service's API key for development time. This way, your user secret (test API key) is not accidentally get checked in
- For production, you set the production service's API key as an Environment Variable on Azure Portal. Your config will be able to read it from there

Please note that nowhere in this workflow, encryption is not in the picture. 

If you also want to encrypt any kind of data, you'll need to use `Microsoft.AspNet.DataProtection` package.  You should check the [docs](http://docs.asp.net/en/latest/security/data-protection/using-data-protection.html?highlight=dataprotection) for that one as well.  You can add any encryption and decryption logic to your app itself.

@danroth27 We need more documentation around this to clarify these concepts to our users.

**Comment by ridercz** [comment]
@muratg Yes, it now makes sense. I intended to write something like `Microsoft.AspNet.DataProtection` and was looking into secure way to store my "machine keys", I was not aware of that it already exists in form of the above.

> We need more documentation around this to clarify these concepts to our users.We need more documentation around this to clarify these concepts to our users.
Yes, yes and thousand yes! That's the conceptual documentation I'm talking about, which is missing form ASP.NET 5. There is a lot of "quickstart" samples, but that's all. And sadly, nobody else than ASP.NET team could write that kind of documentation.
