### ISSUE TITLE
Guidance on deployment of secrets

### ISSUE THREAD

**Issue by brockallen** [aspnet/UserSecrets#45]
It'd be good to have some guidance on how to use secret-manager when deploying an ASP.NET 5 application or how you envision secrets.json to be deployed from a staging environment to a production environment.

**Comment by brockallen** [comment]
It'd be good to have some guidance on how to use secret-manager when deploying an ASP.NET 5 application.

**Comment by Eilon** [comment]
Secrets are generally needed only on the local dev machine. On the production server you might use environment variables, or you might use a file-based provider but pointing to a file that is available only on the server.

**Comment by brockallen** [comment]
Ok, so you don't foresee people taking the local json secret file and pushing that to prod. Yea, I guess given the overriding nature, env variables would fit in there nicely. Ok, thanks.

**Comment by Eilon** [comment]
@blowdart for ultimate guidance.

I'm pretty sure the user secrets are intended for local dev only and not about pushing them out. In principle they could be encrypted, and if they are, they would presumably encrypted with a per-user key, so transferring them to another machine that runs with a different account wouldn't help.

**Comment by blowdart** [comment]
I only viewed user secrets as a local dev solution, meant to keep things out of source control.

**Comment by brockallen** [comment]
Yep, understood. Thanks.

**Comment by muratg** [comment]
For other folks who may be checking this issue, [here](https://github.com/aspnet/UserSecrets/issues/44#issuecomment-147473654)'s some more information on this, with a development scenario.

@danroth27 We should write doc (or at least a blog post) to describe the goals of this tool.
