### ISSUE TITLE
Secrets are Accessible Using Task Runners

### ISSUE THREAD

**Issue by edrohler** [aspnet/UserSecrets#54]
I am using gulp-azure-storage and was using an additional file at the solution level, "secrets.json" which contained the storage connection string to storage. This allowed me to publish static files to a CDN in azure during the build of my static files. Using the file in my %appdata% directory is long and cumbersome. Can we change the location of the secrets file? Also it would be nice to change the name to something that closer matches the xproj name, if we have changed the xproj name. Here is a reference to my project. [MyWebTemplate](https://github.com/edrohler/MyWebTemplate)

**Comment by davidfowl** [comment]
> Can we change the location of the secrets file? 

Probably not, it needs to be per user and the intent is that it's not hidden from you :smile: . It *CANNOT* be anywhere near the project as the entire purpose of this tool is to avoid checking secrets
into source control.

>  Also it would be nice to change the name to something that closer matches the xproj name, if we have changed the xproj name

The name of the file is an implementation detail, in fact, the file should really be encrypted locally on the box but we haven't gotten there yet.

**Comment by muratg** [comment]
@edrohler I want to reiterate that the purpose of this tool is to avoid keeping your secrets in the same folder as your project to avoid accidentally exposing your secrets.  It's a development time tool.

Ideally you would use the configuration system on development (or in build time, for your specific scenario) to store and get the actual production secrets.  You can for example use environment variables on the build machine to store your actual secrets, and user-secrets for your development time secrets.

**Comment by edrohler** [comment]
@davidfowl  and @muratg Thanks. I am aware of the purpose, however, I think the implementation is far less desirable than it could be. For example, I doubt anyone likes to look in their roaming profile for Microsoft for this information (which is defaulted to a hidden folder, by the way) and due to the speed of development in Azure these values change quite quickly. It's not always a set and forget situation. But the use-case for the current implementation implies this. I think this would be better suited in the %USERPROFILE% location which is why I asked if we could change the location. Maybe the tool has a command for the end user to choose which location; is kind of what I was thinking.

Additionally, with the new programming paradigm available in asp.net v5 these secrets are likely to be shared across gulp/grunt, node, asp.net and maybe even jspm which would need a solution level location just to keep it simple. This was also why I was wondering if we could change the location.

For the name change, I think the tool should have a command to change the name of the secrets folder and project.json reference. I realize that I could just change the folder name and the project.json reference but this seems like a little too much overhead for something that is available as a tool. I mean, I have created several new asp.net 5 templates and finding some things work and others don't; having to delete and start over with the things that do work and then find that minor changes like the name of a secret.json file was all that was blocking;  so being able to have that level of control is important.

Anyway, luckily it is another opt-in type situation and I just used .gitignore to ignore the file at the solution level. From there I can use it with gulp and add it to the asp.net startup class. Seems to work for now. I think this aligns more closely with the old remapping of appsettings in web.config/app.config to an external file as well.

**Comment by natemcmaster** [comment]
This repository is now deprecated. I'm closing this issue as we don't intend to take further action to address this issue. If you feel this issue should still be addressed, issues for UserSecrets can be opened on its new home at https://github.com/aspnet/DotNetTools.

cref https://github.com/aspnet/Announcements/issues/206.
