### ISSUE TITLE
Lack of "optional" parameter in AddUserSecrets method

### ISSUE THREAD

**Issue by folarix** [aspnet/UserSecrets#66]
ConfigurationBuilder extension method AddUserSecrets should have an overloaded version with additional Optional(boolean) parameter. This param should be propagated to AddJsonFile method. Without it it's almost impossible to debug any issues related with the incorrect path to secrets file. I recently had an issue with application redirecting %AppData% to C:\Windows\system32\config\systemprofile\AppData\Roaming  instead of C:\Users\MyUsername\AppData\Roaming and I actually had to get the code from git and manually debug it in order to find out that secrets.json has not been found.

**Comment by muratg** [comment]
What would this parameter do exactly?

Putting this in 1.0.0 for now, to consider post RC2.

**Comment by natemcmaster** [comment]
This repository is now deprecated. I'm closing this issue as we don't intend to take further action to address this issue. If you feel this issue should still be addressed, issues for UserSecrets can be opened on its new home at https://github.com/aspnet/DotNetTools.

cref https://github.com/aspnet/Announcements/issues/206.
