### ISSUE TITLE
AddUserSecrets() should use configurationBuilder.GetFileProvider() to read from project.json

### ISSUE THREAD

**Issue by divega** [aspnet/UserSecrets#70]
Based on the discussion with @DamianEdwards @glennc @davidfowl and others today, the UserSecrets configuration provider should read project.json from the same location used for configuration files, i.e. it should use the `IFileProvider` obtained from `configurationBuilder.GetFileProvider()` to read the file. 

In addition, if the project.json file is not found it shouldn't fail.

@muratg we need someone to make this change for RC2.

**Comment by muratg** [comment]
@BrennanConroy can you take this?

I assume this still won't solve https://github.com/aspnet/UserSecrets/issues/62...

**Comment by divega** [comment]
@BrennanConroy I already asked @smitpatel to fix https://github.com/aspnet/Configuration/issues/422. Once we have `configurationBuilder.GetBasePath()` you should use in this fix. Please coordinate with @smitpatel in case one of you wants to take over the whole fix.

**Comment by divega** [comment]
Actually scratch most of that. UserSecrets should not call `builder.GetBasePath()` but `builder.GetFileProvider()` to get access to the project.json file. I will update the description of the bug.

**Comment by BrennanConroy** [comment]
Fixed via 6cc00396d4a9f2368310930e8e6d96ba792f1881
