### ISSUE TITLE
Improve `dotnet user-secrets {command} --project {path}` error messages

### ISSUE THREAD

**Issue by dougbu** [aspnet/UserSecrets#78]
The error message displayed when `{path}` is invalid is not descriptive and references an argument rather than the command-line option.

For example,
```
dotnet user-secrets list --project \garbage
```
Results in
```
critical: Command failed : The directory name C:\garbage\ is invalid.
Parameter name: path
```

Note the parameter name mentioned above is inconsistent w/ the in #77. It's the same command-line option and the parameter should also be the same.

**Comment by muratg** [comment]
Fit & finish bug. Moving to 1.0.1 for now.

**Comment by natemcmaster** [comment]
This issue was moved to aspnet/DotNetTools#171
