### ISSUE TITLE
`dotnet user-secrets` commands do not support nested JSON arrays and objects

### ISSUE THREAD

**Issue by dougbu** [aspnet/UserSecrets#79]
Though configuration files (and therefore `secrets.json` files) support the full breadth of JSON syntax, `dotnet user-secrets` does not. Comments are correctly ignored but that's it.
```
dotnet user-secrets list
```
When the `secrets.json` file contains
```
{
  "L1": {
    // This is a supported comment.
    "Dictionary": {
      "k1": "v1",
      "k2": 425,
      "ă2": "ő23"
    }
  }
}
```
Results in
```
info: L1 = {
  "Dictionary": {
    "k1": "v1",
    "k2": 425,
    "─â2": "┼æ23"
  }
}
```
The configuration framework would treat the above identically to
```
{
  "L1:Dictionary:k1": "v1",
  "L1:Dictionary:k2": 425,
  "L1:Dictionary:ă2": "ő23"
}
```

Similarly, with the original `secrets.json` file, `dotnet user-secrets remove L1:Dictionary` finds nothing to remove and `dotnet user-secrets set L1:Dictionary Fred` creates a new, separate key named `L1:Dictionary`.

**Comment by dougbu** [comment]
In my example above, `dotnet user-secrets set L1:Dictionary:k2 Fred` would mostly work :ok:. It wouldn't update the existing `L1:Dictionary` object. But the configuration system would read the new key last, overriding the value from that object.

Problems are most obvious when attempting to remove properties of JSON objects. Users need to fall back to hand-editing the `secrets.json` file. (Arrays too but they're less useful in our configuration system.)

**Comment by natemcmaster** [comment]
PR #94 changes the CLI tool to use Configuration.AddJsonFile(). This better supports nested objects during reading the secrets.json file. This means the tool will lose info about the original file structure, so nested objects are flattened into key/value pairs when modifying the file.
