### ISSUE TITLE
Support for .NETFramework,Version=v4.5.2?

### ISSUE THREAD

**Issue by dmcweeney** [aspnet/UserSecrets#90]
Hi,

I'm trying to add Microsoft.Extensions.SecretManager.Tools package to my ASP.Net Core project. The project was created with the VS 2015 Update 3 template ASP.Net Core Web Application (.Net Framework). I'm getting the following error:
The dependency Microsoft.Extensions.SecretManager.Tools 1.0.0-preview2-final does not support framework .NETFramework,Version=v4.5.2.

Are there plans to add .NetFramework support for SecretManager?
The other Microsoft.Extensions.Logging and Microsoft.Extensions.Configuration packages have.

Thanks

Donal

**Comment by BrennanConroy** [comment]
SecretManager is a tool, you put it in the `tools: {}` section of your project.json and it shouldn't matter what frameworks you target.

**Comment by dmcweeney** [comment]
Do you not have to add Microsoft.Extensions.SecretManager.Tools to be able to call ConfigurationBuilder.AddUserSecrets() from Startup?

Am I logging this in the wrong place?

**Comment by BrennanConroy** [comment]
You need to add `Microsoft.Extensions.Configuration.UserSecrets` to get `AddUserSecrets()`
The tool is used for managing your secrets from the command line like: `dotnet user-secrets add <key> <value>`

**Comment by dmcweeney** [comment]
I put this down to Monday blues!

I searched package manager for "secret" (not pural) and Microsoft.Extensions.SecretManager.Tools comes up as one of the search results.

This morning if I search for "secrets" (pural)  Microsoft.Extensions.Configuration.UserSecrets  comes up in the search hits.

I see it now.

Thanks

Donal
