### ISSUE TITLE
Make tool more friendly in usage from other tooling.

### ISSUE THREAD

**Issue by phenning** [aspnet/UserSecrets#95]
For example, in order to display a grid, you would need to parse out the info: output from the results of dotnet user-secrets list. Ideally, this should just be a --json or similar switch which would just output the secrets as json.

Similarly, it would also be good to be able to pass in json via the set command, bonus if nested json could be passed in here and the tool would take care of flattening.

**Comment by natemcmaster** [comment]
This issue was moved to aspnet/DotNetTools#168
