### ISSUE TITLE
Find a new location for userSecretsId as dotnet CLI moves to use csproj instead of project.json

### ISSUE THREAD

**Issue by muratg** [aspnet/UserSecrets#96]
Slightly related #62. 

Since project.json is going away, we'll need to resolve this soon.

@glennc @davidfowl @natemcmaster @Tratcher

**Comment by natemcmaster** [comment]
Just brainstorming: here are some options

 - A special purpose setting file,`usersecrets.json`, in project root. Works the same as project.json does today. Ms.Ext.Config.UserSecrets [extends the build target](https://docs.nuget.org/create/creating-and-publishing-a-package#import-msbuild-targets-and-props-files-into-project) to ensure the file is copied to build folder.
 - A general setting file, like `appsettings.json` (or `web.config` :trollface: )
 - A well-known MSBuild property `<UserSecretId>XXXX-XXXX</UserSecretId>`
    - Requires adding a target to generate a resource for config to read at runtime such as
       - an assembly attribute
       - a config file in app base dir
    - CLI tool
        - runs inside build: `dotnet user-secrets` becomes alias for `dotnet msbuild /t:UserSecrets`
        - otherwise, CLI tool hosts MSBuild and does a [design time build](https://github.com/dotnet/roslyn-project-system/blob/7463c45b7f3bdf851f8da157f7b65236f87102c2/docs/design-time-builds.md) to extract the property value. (See [early implementation](https://github.com/aspnet/EntityFramework/blob/65ef9a6c53e077e0028a32ef4b3029b31ec0728c/src/Tools.DotNet/Internal/MsBuildProjectContext.cs) of something similar in dotnet-ef)

**Comment by glennc** [comment]
msbuild seems the best option here. But why does there need to be a special file generated? Why can there not be a config source that reads from a csproj?

It is just data in the csproj.

**Comment by Tratcher** [comment]
The csproj isn't published

**Comment by natemcmaster** [comment]
IMO keeping the id in a simple file such as `usersecrets.json` or `.usersecretrc` is the better option. Adding as a property in MSBuild is going to be more complicated and have little benefit

**Comment by davidfowl** [comment]
What about `appsettings.json` and we pass the filename into the `AddUserSecrets`. It's a bit of a breaking change.

**Comment by natemcmaster** [comment]
Design from in-person discussion with @glennc and @davidfowl:

1. The value of userSecretId can be in any json file. Templates and tools will default to a file named `appsettings.json`. Users could configure it to 'project.json' if they still want

   ```json
   {
       "userSecretId": "xxxx-xxxx"
   }
   ```

1. `UserSecretIdentifierFileAttribute` will be generated during build using a task imported from the `Microsoft.Extensions.Configuration.UserSecrets` nupkg. The value of the attribute is configured from a property in the csproj. This will be in templates. It will default to appsettings.json if not present.
    ```xml
    <PropertyGroup>
        <UserSecretIdentifierFile>appsettings.json</UserSecretIdentifierFile>
    </PropertyGroup>
    ```
1. Runtime: `.AddUserSecrets()` will look for an assembly attribute, `UserSecretIdentifierFileAttribute` and read userSecretId from the file. As with other config files, we will assume the path is relative to `ConfigurationBuilder.GetFileProvider()`.
1. Design-time tooling: VS can identify which file to use by evaluating the csproj. CLI can take a command line flag to point to a different JSON file.

**Comment by muratg** [comment]
Will the attribute be a top-level attribute in the Json file (as it is today?)

**Comment by natemcmaster** [comment]
Yes. The JSON part of this doesn't change much. We are just going to remove the strict requirement that the JSON file be named project.json. (See #103)

**Comment by natemcmaster** [comment]
This issue was moved to aspnet/DotNetTools#169
