### ISSUE TITLE
No executable found matching command 

### ISSUE THREAD

**Issue by shahriarhossain** [aspnet/UserSecrets#97]
I have added "Microsoft.Extensions.SecretManager.Tools": "1.0.0-preview2-final" in project.json
Whenever I am trying to **_dotnet user-secrets -h_**
I am getting this reply : [1m[31mNo executable found matching command "dotnet-user-secrets"[39m[22m in the console

**Comment by BrennanConroy** [comment]
Did you put `Microsoft.Extensions.SecretManager.Tools` in the "tools" section of project.json? Did you run `dotnet restore` to download the tool before trying to use it?

**Comment by natemcmaster** [comment]
Two more things: 
Did you execute from the directory holding project.json? 
Which version of the .NET Core SDK is installed? (`dotnet --info` will show you the version)

**Comment by shahriarhossain** [comment]
Oops! My bad, I was adding the **Microsoft.Extensions.SecretManager.Tool** in the "dependencies" section. After adding the following segment in the "tools" section everything working properly. 
    "Microsoft.Extensions.SecretManager.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
Thanks @BrennanConroy and @natemcmaster
